
name = "DashDragGrid"
uuid = "1b08a953-4be3-4667-9a23-4015cbeafbd6"
authors = ["Simon Unterbusch <simonunterbusch@unterbusch.com>"]
version = "0.99"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
